# Generated by Django 4.0.8 on 2022-12-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
